Default: &defaults
  database: campaign-next.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: campaign-next_test.sqlite3
  <<: *defaults

Staging:
  database: campaign-next_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: campaign-next_production.sqlite3
  poolsize: 100
  <<: *defaults
